name: Deploy to VPS

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: scp -r ./* anas@195.110.58.197:/var/www/laravel-lakkta

    - name: Run deployment script
      run: ssh anas@195.110.58.197 'bash /home/anas/deployment-scripts/deploy.sh'